export const GET_STACK_OPTIONS = {
  REQ: "GET_STACK_OPTIONS",
  RES: "RES_STACK_OPTIONS",
  FAIL: "FAIL_STACK_OPTIONS",
};

export const GET_VENDOR_OPTIONS = {
  REQ: "GET_VENDOR_OPTIONS",
  RES: "RES_VENDOR_OPTIONS",
  FAIL: "FAIL_VENDOR_OPTIONS",
};
